AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'test/internal/db/*'
Metrics/LineLength:
  Max: 150
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
